### PR TITLE
Adds link to maintained fork

### PR DESCRIPTION
**Pull request by get-got**

### CODE REVIEW

**Comment by drachedachte1** [comment]
Uhm whot lmao

**Comment by get-got** [comment]
@drachedachte1 I made a fork project of this that implements different features, when I sent it to Sekl he said I should make a PR linking to it in the readme since this project isn't often maintained anymore.

**Comment by drachedachte1** [comment]
> @drachedachte1 I made a fork project of this that implements different features, when I sent it to Sekl he said I should make a PR linking to it in the readme since this project isn't often maintained anymore.

@get-got what kind of features?

**Comment by get-got** [comment]
@drachedachte1 Configuration is entirely JSON based so there's [extensive customization with settings](https://github.com/get-got/discord-downloader-go#list-of-settings), channel-specific settings and such. Uses latest versions of go & discordgo.

[List of differences here](https://github.com/get-got/discord-downloader-go#differences-from-seklfreaks-discord-image-downloader-go--why-i-made-this)

**Comment by drachedachte1** [comment]
Interesting thx

**Comment by Seklfreak** [comment]
Thanks :)

**Pull request merged**
