### PR TITLE
Another one try of adding new stuff

### PR DESCRIPTION
**Pull request by SLASHLogin**
I hope this time it will end good. If not, please don't close it so fast, beacause I will be trying help you with this so I will change my mistake and adhere to your advices.

### CODE REVIEW

**Comment by SLASHLogin** [comment]
Uh, I don't where I did mistake

**Comment by Seklfreak** [comment]
You didn't add any option to the config file, you just added a variable. Also you shouldn't use `Sprintf` when you aren't formatting any text (you have to add a `%s` placeholder). I'm not sure why you are using `Print`(/`Sprintf`) here at all. I'm sorry but I can't merge this.

**Comment by Seklfreak** [comment]
I'm reopening it in case you want to submit more, but please make sure it works before you submit it.

**Comment by SLASHLogin** [comment]
Thank you so much I will be improving code until I will do that properly. I will add option to config and take look at printing etc.
Anyway sorry because it's not my language and I don't know so good it but I want to help you some way and just trying hard

**Comment by SLASHLogin** [comment]
em okay line 1477 just gimme chance

**Comment by Seklfreak** [comment]
I'm pretty busy at the moment but I will look at it, and fix what needs to be fixed when I got time. Please allow me some time. :)

**Comment by SLASHLogin** [comment]
I don't see any problems. As I said (or not I'm not sure now) it's completely new lang so sorry for my incompetence

**Pull request closed without merging**
