### PR TITLE
Added queue functionality to the history command

### PR DESCRIPTION
**Pull request by EnanoFurtivo**
This same piece of code can be found at https://pastebin.com/MBhFQfHQ
Edited by EnanoFurtivo: https://github.com/EnanoFurtivo/discord-image-downloader-go
Sourcecode by Selfreak: https://github.com/Seklfreak/discord-image-downloader-go

This code adds the functinality to queue more than one channel id for history donwload at a time

Edited file main.go in 'Case == history'

IMPORTANT: in the main.go that is uploaded in my github i had to delete a bunch of code due to a to a problem with mvdan.cc library. Still i was able to compile and test the functionality of the added feature. Something to have in mind is that the piece of code below is complete and nothing was substracted from it only it was added with the for function wich allows this modification to work (nothing else is needed). If you replace this into the original main.go from Selfreak and you manage to fully compile, all of the original functionalities should still be working just fine plus the added for functionality.

Modified piece of code can be found at the pastebin above or on the Changes Readme.txt attached to the main branch

### CODE REVIEW

**Comment by EnanoFurtivo** [comment]
Btw im new to github so i dont really know wich type of requesr i have yo use so yeah.

**Comment by Seklfreak** [comment]
Thank you very much! I will take a look on monday

**Comment by Seklfreak** [comment]
Looks great, should be very useful. I updated it to the current version. Thank you very much!

**Comment by EnanoFurtivo** [comment]
Nice, glad the feature made it in! Keep up the good work.

**Pull request merged**
